# Generated by Django 5.2.8 on 2025-11-13 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='user_', help_text='Öffentlicher Benutzername, z. B. für Posts.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username darf nur Buchstaben, Zahlen und Unterstriche enthalten.', regex='^[a-zA-Z0-9_]+$')], verbose_name='username'),
        ),
    ]
