# Generated by Django 5.2.8 on 2025-11-17 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_rule_unique_together_remove_rule_community_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('position', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='forum_post_is_pinn_31ebda_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_pinned',
        ),
        migrations.AddField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forum.post'),
        ),
    ]
