# Generated by Django 5.2.8 on 2025-11-17 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_postimage_remove_post_forum_post_is_pinn_31ebda_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_pinned'], name='forum_post_is_pinn_31ebda_idx'),
        ),
    ]
